package com.mend.domain.enums;

public enum AuditEventType {
    WEBHOOK_RECEIVED,
    CLASSIFICATION_CREATED,
    STRATEGY_ASSIGNED,
    STATE_TRANSITION,
    COMPLIANCE_ALLOWED,
    COMPLIANCE_BLOCKED,
    ACTION_INTENT_CREATED,
    ACTION_EXECUTED,
    ACTION_FAILED,
    CAMPAIGN_RECOVERED,
    CAMPAIGN_ESCALATED,
    REVIEW_DECISION
}
